### ISSUE TITLE
Ajustar Readme del CRUD

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/movilidad_academica_crud#1]
Realizar la documentación

**Comment by grumysh** [comment]
Ajustar readme de repositorio teniendo en cuenta los lineamientos de la oficina: https://github.com/udistrital/introduccion_oas/blob/master/repositorios_institucionales/contenido_readme.md

**Comment by BOTOOM** [comment]
se definen 2 horas para realizarce

**Comment by Soulfilip-UD** [comment]
Se realizo una buena documentación , por lo tanto se da por finalizado el Issue
