### ISSUE TITLE
Establecer el modelo de la db 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/movilidad_academica_crud#2]
Establecer el modelo de la db con el cual se trabajara el crud de la aplicacion de movilidad academico CERI, este  se disella  en el Issues #3

**Comment by grumysh** [comment]
![IMG_20190522_103300_571](https://user-images.githubusercontent.com/29903400/58194857-410ac000-7c8c-11e9-8d27-495621330c30.jpg)
