### ISSUE TITLE
Diseñar el modelo de la BD

### ISSUE THREAD

**Issue by grumysh** [udistrital/movilidad_academica_crud#3]
Diseñar el modelo planteado en #2 en el pgModeler y generar el sql de creación de la Base de datos.

**Comment by grumysh** [comment]
Script de creación de la base de datos.

[ceri.zip](https://github.com/udistrital/movilidad_academica_crud/files/3208592/ceri.zip)

**Comment by grumysh** [comment]
![modelo de bd del ceri](https://user-images.githubusercontent.com/29903400/58199883-16723480-7c97-11e9-839e-c30e600df408.png)

**Comment by Soulfilip-UD** [comment]
La tarea se finalizo, se documento y se da el Issue por finalizado.
